#!/usr/bin/python3
from sys import argv
import time
import os
def factors():
    start = time.time()
    with open(argv[1]) as f:
        for line in f:
            div = 2
            try:
                num = int(line)
                while True:
                    end = time.time()
                    if ((end - start) > 5):
                        os.system('pkill -f factors')
                    if (num == 0 or num == 1):
                        print("{}={}*{}".format(num, num, num))
                        break
                    if num % div == 0:
                        result = int(num / div)
                        print("{}={}*{}".format(num, result, div))
                        break
                    else:
                        div += 1
            except (ValueError, TypeError) as error:
                import sys
                continue
                #print("Exception: {}".format(error), file=sys.stderr)

    

factors()
